### PR TITLE
Make local dev consistent with other apps

### PR DESCRIPTION
**Pull request by Halama**
Jenom drobné zjednodušení local dev.

### CODE REVIEW

**Review by pivnicek — COMMENTED** [review]
nebude fungovat bez KBC_CONFIG_ID apod ne?

**Comment by Halama** [comment]
nic takovýho jsem tam nenašel

**Comment by Halama** [comment]
viz. https://travis-ci.com/github/keboola/data-loader/settings a https://github.com/keboola/data-loader/blob/2dbe5f6ba93a50c56fc3f8e3ebdc89d514765a86/.travis.yml#L8

**Comment by pivnicek** [comment]
I was thinking of this 
https://github.com/keboola/data-loader/blob/master/src/ConfigValidator.php#L123

**Comment by Halama** [comment]
tests are successful and it wasn't mentioned in doc

**Comment by pivnicek** [comment]
ok, it was something I thought of because I remember it from here 
https://github.com/keboola/docker-jupyter/blob/master/docker-compose.yml#L11

**Comment by Halama** [comment]
It looks like it is generated and injected in tests https://github.com/keboola/data-loader/blob/1dc24444b86d2530c1950bfd510e0d6690dfafe1/tests/phpunit/ConfigValidatorTest.php#L32

**Comment by odinuv** [comment]
yeah, you need the KBC_CONFIG_ID and stuff only to actually run it, not for executing tests, should be ok

**Review by odinuv — APPROVED** [review]

**Pull request merged**
