### PR TITLE
PS-801 workspace staging

### PR DESCRIPTION
**Pull request by pivnicek**
https://keboola.atlassian.net/browse/PS-801

So, it will need `WORKSPACE_ID` and `WORKSPACE_PASSWORD` in the environment, and if it sees those it will use the workspace as data staging

### CODE REVIEW

**Comment by pivnicek** [comment]
sorry for the premature review request @JakubMatejka , it needed some cs and stan touches.  All good now.

**Comment by JakubMatejka** [comment]
So it needs workspace password too? How it will work for additional data loads after the sandbox is created? (But that handles the API, not this one, right?)

**Comment by pivnicek** [comment]
Yes, unfortunately it's required.  diskuze: https://keboola.slack.com/archives/CN8G7T9CP/p1597059345010700

the dl-api will get it the same way, via env on initialization

**Comment by JakubMatejka** [comment]
aha, on init, good.

**Review by JakubMatejka — APPROVED** [review]
👍

**Pull request merged**
